### PR TITLE
Add compatibility to Cowboy 2

### PR DESCRIPTION
**Pull request by ThomasHaddad**

### CODE REVIEW

**Comment by akira** [comment]
👍 thanks!

**Comment by akira** [comment]
@ThomasHaddad I noticed some issues in with this (for some reason test failure did not report in your PR on github):

```
==> exq_ui
** (Mix) Could not compile dependency :cowlib, "/Users/akira/.mix/rebar3 bare compile --paths "/Users/akira/development/erlang/exq_ui/_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile cowlib", update it with "mix deps.update cowlib" or clean it with "mix deps.clean cowlib"
```

For example, see: https://travis-ci.org/akira/exq_ui/jobs/433926717  - This also happens locally. Any ideas on this?

**Comment by ThomasHaddad** [comment]
@akira i'll take a look at this as soon as i can

**Comment by ThomasHaddad** [comment]
@akira cowboy 2 only supports now OTP19 and newer (see https://ninenines.eu/docs/en/cowboy/2.5/guide/introduction/). I didn't see that you were running specs on lower versions.

**Comment by ThomasHaddad** [comment]
See https://github.com/akira/exq_ui/pull/61

**Pull request merged**
