### PR TITLE
Add support for live view 0.17

### LINKED ISSUE #108: Dependency issue with phoenix live view
I'm running Live View 0.17.5, and version 12 is locked on `exq_ui (version 0.12.0) requires ~> 0.16.0`

Can the dependency be bumped to allow for version PLV 17?

### PR DESCRIPTION
**Pull request by ananthakumaran**
fixes #108 

`<%= live_component` has not been updated to the new format `<.live_vew` since that would break the compatibility with phoenix live view 0.16. I have tested the changes with both 0.16 and 0.17. Both works, though 0.17 will show deprecation messages.

### CODE REVIEW

**Comment by ananthakumaran** [comment]
@jpea72 you can try out this branch. I plan to merge this branch to master in couple of days.

**Comment by SebastianSzturo** [comment]
Can we get a new version with this change 🙏🏻

**Comment by ananthakumaran** [comment]
\cc @akira maybe we can release exq and exq_ui. Few mrs has been merged since the last release.

**Comment by akira** [comment]
Thanks I will release it this weekend!

**Comment by akira** [comment]
@SebastianSzturo @ananthakumaran just released exq_ui 0.12.1, sorry for delay

**Pull request merged**
