### PR TITLE
Button for immediate retries

### PR DESCRIPTION
**Pull request by chelsea**
Addresses #5 

Adds a button to the retry page which immediately retries the job.

Also updates the test suite to work with the latest version of exq with customisable serialisation.

Updated `ember_validations` as the previous URL source is no longer available.

I'm a bit lost as to how to get the ember app to be updated after https://github.com/akira/exq_ui/pull/24 though, everything works fine running locally with `path` set and `ember server` running, but trying to reference my fork of exq_ui results in nothing rendering.

### CODE REVIEW

**Comment by chelsea** [comment]
Because this depends on changes that aren't in a versioned release of exq I built directly against master which is why there are the serialiser changes. 

I could make the retry bit backwards compatible and only do something with the button if the `retry_job` function exists, but I wasn't entirely sure it was worthwhile at this point. And the test suite would still need updating when a new exq version gets cut.

**Comment by akira** [comment]
@chelsea Don't worry about making it backwards compatible.  I will release an updated version of Exq and bump the version required for ExqUI.  

Thanks!

**Comment by akira** [comment]
@chelsea FYI at some point I may convert this to either ReactJS or VueJS, as I don't have as much Ember experience and probably will not learn it (given I probably won't be using Ember for any future projects).

**Comment by chelsea** [comment]
Thanks for that, I'll leave things alone and update the exq dependency when a new one is cut.

This has been my first time working with ember, so I'm really not sure if I've done things correctly, I've mostly just guessed at it for this PR and it seemed to work.

**Comment by akira** [comment]
Ran tests locally.  Merging and will bump dependency. 

Thanks!  ✨✨

**Pull request merged**
